### PR TITLE
feat(vue): add v-model support to ix-select and ix-toggle

### PR DESCRIPTION
**Pull request by tiagogviegas**
## 💡 What is the current behavior?

IxSelect and IxToggle don't support v-model directive out of the box. Being components that often are used in form control v-model support should exist.

## 🆕 What is the new behavior?

- Updated vueOutputTarget options to enable support for v-model binding in ix-select and ix-toggle.

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [ ] 🦮 Accessibility (a11y) features were implemented
- [ ] 🗺️ Internationalization (i18n) - no hard coded strings
- [ ] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [ ] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [ ] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [ ] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [x] 🧐 Static code analysis passes (`pnpm lint`)
- [x] 🏗️ Successful compilation (`pnpm build`, changes pushed)

### CODE REVIEW

**Review by nuke-ellington — COMMENTED** [review]
PR looks good but it might look even nicer if we could set up v-model support for all iX components ;-) Not sure how much effort this would be though..

**Comment by tiagogviegas** [comment]
> PR looks good but it might look even nicer if we could set up v-model support for all iX components ;-) Not sure how much effort this would be though..

Do we have a list of which components make sense to add v-model support? In my opinion it would only make sense to add it to components which have a 2-way data binding logic.

**Comment by nuke-ellington** [comment]
> > PR looks good but it might look even nicer if we could set up v-model support for all iX components ;-) Not sure how much effort this would be though..
> 
> Do we have a list of which components make sense to add v-model support? In my opinion it would only make sense to add it to components which have a 2-way data binding logic.

Unfortunately no. One would have to check all components manually.

**Comment by danielleroux** [comment]
We be implemented in https://github.com/siemens/ix/pull/1318

Also found an bug inside stencil vue output target which is patched in PR https://github.com/siemens/ix/pull/1318/files#diff-20e3815ee3dd23189c10abdc94e28f41885810c2e2bea70ff209834f5f9121b8R9-R11

Close this one here

**Pull request closed without merging**
