### PR TITLE
docs(search): add basic index search

### PR DESCRIPTION
**Pull request by danielleroux**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Unit tests (`yarn test`) were run locally and passed
- [ ] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [ ] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bug fix
- [x] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the new behavior?

- Implement basic search based on lunr local search plugin https://github.com/praveenn77/docusaurus-lunr-search
- Swizzle SearchBar components (keep existing more or less "bad code")
- Tag search is currently no supported (https://github.com/praveenn77/docusaurus-lunr-search/issues/81) #63 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by nuke-ellington — COMMENTED** [review]
Cannot review the search functionality since the input field says Loading.. and will not change.

**Comment by danielleroux** [comment]
> Cannot review the search functionality since the input field says Loading.. and will not change.

You have to build docusaurus, because index is only generated during build time.

```
yarn build
yarn workspace documentation serve
```

**Comment by nuke-ellington** [comment]
@danielleroux Search looks nice :) But somehow theme is not loading in playground it seems:

Screenshot 2023-01-13 at 11 09 52

**Comment by danielleroux** [comment]
> @danielleroux Search looks nice :) But somehow theme is not loading in playground it seems:
> 
> Screenshot 2023-01-13 at 11 09 52

@nuke-ellington Cannot reproduce this behavior 👀

**Review by nuke-ellington — APPROVED** [review]
lgtm

**Pull request merged**
