### PR TITLE
docs: remove auto-generated content

### PR DESCRIPTION
**Pull request by sisp**
## Summary

I've removed auto-generated content files in the documentation in the directory `packages/documentation/docs/auto-generated/*` because it's not necessary to version them via SCM and merely pollutes the repository. To prevent them from being added again in the future, I've added a `.gitignore` file in the documentation package that excludes this path.

See also https://github.com/siemens/ix/pull/116#issuecomment-1303973850.

## How did you test this change?

There's not much to test. These files are generated by [packages/documentation/scripts/generate-api.mjs](https://github.com/siemens/ix/blob/67ff00837402b6041c117f40146bcaff62a37b85/packages/documentation/scripts/generate-api.mjs) which is run as part of the docs build process:

https://github.com/siemens/ix/blob/67ff00837402b6041c117f40146bcaff62a37b85/packages/documentation/package.json#L8

Not versioning them via SCM won't prevent them from being published on the docs site.

### CODE REVIEW

**Comment by sisp** [comment]
Interesting, a few imports can't be resolved anymore, which means some of the auto-generated docs files weren't actually generated anymore. No error had occurred before because those obsolete files were still available in the repo.

**Comment by sisp** [comment]
I've removed unused/unresolvable imports for the map navigation component. But there's still the following error:

```
Module not found: Error: Can't resolve './../auto-generated/previews/angular/tabs-rounded.md' in 'siemens-ix/packages/documentation/docs/controls'
```

The auto-generated `tabs-rounded.md` files for React and Web Components but not for Angular. :thinking: Any idea what's wrong here?

**Comment by danielleroux** [comment]
> I've removed unused/unresolvable imports for the map navigation component. But there's still the following error:
> 
> ```
> Module not found: Error: Can't resolve './../auto-generated/previews/angular/tabs-rounded.md' in 'siemens-ix/packages/documentation/docs/controls'
> ```
> 
> The auto-generated `tabs-rounded.md` files for React and Web Components but not for Angular. 🤔 Any idea what's wrong here?

yep because the file is missing here: https://github.com/siemens/ix/blob/main/packages/angular-test-app/src/preview-examples

I fix this asap

**Comment by sisp** [comment]
The CI checks are passing now. :tada:

**Review by danielleroux — APPROVED** [review]
lgtm

**Pull request merged**
