### PR TITLE
fix(card-list): fixed card-list show all ellipsis issue

### PR DESCRIPTION
**Pull request by ridvandmrc**
## 💡 What is the current behavior?
When the title of a card-list card becomes too long, the "Show all" - action is not completely visible anymore.

GitHub Issue Number: #1295 

## 🆕 What is the new behavior?

- show more is not shrink 
- title is getting short and ellipsis

## 🏁 Checklist

A pull request can only be merged if all of these conditions are met (where applicable):

- [] 🦮 Accessibility (a11y) features were implemented
- [X] 🗺️ Internationalization (i18n) - no hard coded strings
- [X] 📲 Responsiveness - components handle viewport changes and content overflow gracefully
- [X] 📄 Documentation was reviewed/updated (`pnpm run docs`)
- [] 🧪 Unit tests were added/updated and pass (`pnpm test`)
- [X] 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
- [X] 🧐 Static code analysis passes (`pnpm lint`)
- [X] 🏗️ Successful compilation (`pnpm build`, changes pushed)

### CODE REVIEW

**Comment by ridvandmrc** [comment]
It looks like:
image

**Comment by danielleroux** [comment]
@ridvandmrc Thanks for PR

> 🧪 Unit tests were added/updated and pass (pnpm test)
 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
 🧐 Static code analysis passes (pnpm lint)
 🏗️ Successful compilation (pnpm build, changes pushed)


You marked everythink as checked, but build does not work because of linting error also testcases are missing here. Is this PR still in draft?

**Comment by ridvandmrc** [comment]
> @ridvandmrc Thanks for PR
> 
> > 🧪 Unit tests were added/updated and pass (pnpm test)
> > 📸 Visual regression tests were added/updated and pass ([Guide](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md#visual-regression-testing))
> > 🧐 Static code analysis passes (pnpm lint)
> > 🏗️ Successful compilation (pnpm build, changes pushed)
> 
> You marked everythink as checked, but build does not work because of linting error also testcases are missing here. Is this PR still in draft?

Yes it is still draft, give me a second to update

**Comment by danielleroux** [comment]
/snapshots:approve --args=card-list.e2e --sha=9774f4b002e7de4914c3406b1e82a41d475bb4cf

**Review by danielleroux — APPROVED** [review]

**Review by nuke-ellington — APPROVED** [review]

**Pull request merged**
