### PR TITLE
fix(core/modal): fixed closing modal issue when press space or enter

### PR DESCRIPTION
**Pull request by ridvandmrc**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`yarn build`) was run locally and any changes were pushed
- [X] Unit tests (`yarn test`) were run locally and passed
- [X] Visual Regression Tests (`yarn visual-regression`) were run locally and passed
- [X] Linting (`npm lint`) was run locally and passed

## Pull request type

Please check the type of change your PR introduces:

- [X] Bug fix
- [ ] Feature
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?
The modal is closing when focus some input element and press 'space'

GitHub Issue Number: #1077 

## What is the new behavior?
The reason was that clickoutSide is triggered when press the space,
I checked that if the event is pointer event (click or touch) or not

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by danielleroux** [comment]
How do you think about using the check if the event target is not the dialog element itself then closing the modal?

```tsx
  private onModalClick(event: MouseEvent) {
    if (event.target !== this.dialog) {
      return;
    }
```

**Comment by ridvandmrc** [comment]
> How do you think about using the check if the event target is not the dialog element itself then closing the modal?
> 
> ```tsx
>   private onModalClick(event: MouseEvent) {
>     if (event.target !== this.dialog) {
>       return;
>     }
> ```

**Comment by ridvandmrc** [comment]
> > How do you think about using the check if the event target is not the dialog element itself then closing the modal?
> > ```tsx
> >   private onModalClick(event: MouseEvent) {
> >     if (event.target !== this.dialog) {
> >       return;
> >     }
> > ```

**Comment by ridvandmrc** [comment]
@danielleroux , It worked and clear already fixed

**Comment by danielleroux** [comment]
Looks good. I will add some tests after merge.

**Review by danielleroux — APPROVED** [review]

**Pull request merged**
